name: Notify on PR

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

permissions:
  actions: write    # Required to trigger workflow runs
  contents: read    # Required to check out code
  pull-requests: read    # Required to read PR information

jobs:
    notify:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # - name: notify-PRs
        #   if: github.ref == 'refs/heads/main'
        #   uses: debuide/notify-prs@v1.0
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Check main branch
          if: github.event_name == 'pull_request'
          uses: debuide/base-branch-status@1ec8b06
          with:
            base-branch: develop
            github-token: ${{ secrets.GITHUB_TOKEN }}

