name: Notify on PRs

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

permissions:
  actions: write    # Required to trigger workflow runs
  contents: read    # Required to check out code
  pull-requests: read    # Required to read PR information

jobs:
    notify:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # - name: PRs-Refresh
        #   if: github.ref == 'refs/heads/main'
        #   uses: debuide/pr-refresh@v1.0.0
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#         - name: PRs-Refresh
#           if: github.ref == 'refs/heads/main'
#           uses: krupakar0307/action-pr-triggers@efbf26f7d3b717ec1a6047b02fc232296019d76d
#           env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # - name: Check main branch
        #   if: github.event_name == 'pull_request'
        #   uses: debuide/base-branch-status@v1.0.0
        #   with:
        #     base-branch: main
        #     github-token: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Check main branch
          uses: debuide/merge-guard@c274b507625a09c82dd4e10a24b1e56fa224abb4
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # with:
          #   # silent: true
          #   github-token: ${{ secrets.GITHUB_TOKEN }}
