name: Notify on PR

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    notify:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: notify-PRs
          if: github.ref == 'refs/heads/main'
          uses: debuide/notify-prs@v1.0
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Check main branch
          if: github.event_name == 'pull_request'
          uses: debuide/check-base-branch-status@v1.1
          with:
            base-branch: main
            github-token: ${{ secrets.GITHUB_TOKEN }}

